### ISSUE TITLE
Data journalism and visualization course at the University of Gothenburg, Sweden

### ISSUE THREAD

**Issue by Rybinalla** [jwyg/data-journalism-courses#6]
Name - Data journalism and visualization
Institution – University of Gothenburg, The Department of Journalism, Media and Communication
Country – SE, Sweden
Level – Postgraduate
Type – a 15 ECTS-course, part of a one-year Master Programme taught in English
URL – http://utbildning.gu.se/education/courses-and-programmes/program_detail/?programid=S2JOU

**Comment by jwyg** [comment]
Thanks @Rybinalla!

Just updated: https://github.com/jwyg/data-journalism-courses/commit/2995a04fe446ef618b845f77f2141d83673ed757
