### ISSUE TITLE
Add programs in Kyrgyzstan, Albania and Sudan

### ISSUE THREAD

**Issue by evaconstantaras** [jwyg/data-journalism-courses#8]
“Data Journalism”,”American University of Central Asia”,”KG”,”Undegraduate”,”Programme”,”https://auca.kg/en/auca_news/2962/”
“Data Journalism”,”American University of Central Asia”,”KG”,”Postgraduate”,”Programme”,”https://dss.auca.kg/master-in-journalism-and-mass-communications/”
“Data Literacy”,”University of Khartoum”,”SD”,”Undergraduate”,”Module”,”https://www.sudandata.org/learning/2”
“Data Literacy”,”Ahfad University”,”SD”,”Undergraduate”,”Module”,” https://www.sudandata.org/learning/2”
“Data Journalism”,”University of Tirana”,”AL”,”Undegraduate”,”Module”,”http://www.odecanet.org/data-journalism-manual/”

**Comment by jwyg** [comment]
Thanks so much @evaconstantaras!

Just updated: https://github.com/jwyg/data-journalism-courses/commit/23f676b52d5a9527071add02c91fc0abf51ee525
